### ISSUE TITLE
Export in other format

### ISSUE THREAD

**Issue by mopoIo** [zevaryx/r_place#1]
.gif is pretty difficult to work with when you increase the scale size

**Comment by zevaryx** [comment]
There are other scripts that use my archive and output in different formats. See [Zoruda's fantastic generator]( https://github.com/ZorudaRinku/r-place-timelapse) for one that generates MP4. 

I purposefully decided to stick to gif because that repository exists. I wanted to keep my script as slim as possible, and as such, don't want to have to bundle any external binaries into it.
